apiVersion: v1
kind: Service
metadata:
  name: lite-explorer
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: lite-explorer
